# Generated by Django 3.0.5 on 2020-04-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('serious_critical', models.IntegerField()),
                ('total_cases_1m_pop', models.FloatField()),
                ('deaths_1m_pop', models.FloatField()),
                ('entry_date', models.CharField(max_length=50)),
                ('total_tests', models.IntegerField()),
                ('continent', models.CharField(max_length=50)),
                ('tests_1m_pop', models.CharField(max_length=50)),
                ('total_recovered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_cases_1m_pop', models.FloatField()),
                ('deaths_1m_pop', models.FloatField()),
                ('entry_date', models.CharField(max_length=50)),
                ('total_tests', models.IntegerField()),
                ('tests_1m_pop', models.CharField(max_length=50)),
            ],
        ),
    ]
